
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_gateway_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=payment_gateway
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: payment_gateway_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: payment_gateway
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
